[package]
name = "sub"
version = "0.1.0"
edition = "2021"
description = "A command-line tool for string substitutions"

[dependencies]
assert_cmd = "2.0.16"
clap = { version = "4.5.20", features = ["cargo", "derive"] }
regex = "1.11.1"
atty = "0.2"
